/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/inventory/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_v1_inventory_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust Inventory */
        post: operations["adjust_inventory_v1_inventory_adjustments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Organization */
        get: operations["current_organization_v1_organizations_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles */
        get: operations["roles_v1_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approval-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approval Policies */
        get: operations["approval_policies_v1_approval_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feature Flags */
        get: operations["feature_flags_v1_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustmentResponse */
        AdjustmentResponse: {
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /** Replayed */
            replayed: boolean;
            position: components["schemas"]["InventoryPositionResponse"];
        };
        /** ApprovalPolicyResponse */
        ApprovalPolicyResponse: {
            /** Id */
            id: string;
            /** Action Type */
            action_type: string;
            /** Minimum Approvals */
            minimum_approvals: number;
            /** Approver Permission */
            approver_permission: string;
            /** Amount Threshold */
            amount_threshold: string | null;
            /** Currency */
            currency: string | null;
            /** Active */
            active: boolean;
        };
        /** FeatureFlagResponse */
        FeatureFlagResponse: {
            /** Key */
            key: string;
            /** Enabled */
            enabled: boolean;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InventoryAdjustmentRequest */
        InventoryAdjustmentRequest: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Quantity Delta */
            quantity_delta: number | string;
            /** Uom */
            uom: string;
            /** @default sellable */
            condition: components["schemas"]["StockCondition"];
            /** Lot Id */
            lot_id?: string | null;
            /** Serial Id */
            serial_id?: string | null;
            /**
             * Ownership
             * @default owned
             */
            ownership: string;
            /** Reason Code */
            reason_code: string;
            /** Business Reference */
            business_reference: string;
            /** Expected Version */
            expected_version: number;
            /**
             * Allow Negative
             * @default false
             */
            allow_negative: boolean;
        };
        /** InventoryPositionResponse */
        InventoryPositionResponse: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Uom */
            uom: string;
            condition: components["schemas"]["StockCondition"];
            /** Lot Id */
            lot_id: string | null;
            /** Serial Id */
            serial_id: string | null;
            /** Ownership */
            ownership: string;
            /** On Hand */
            on_hand: string;
            /** Reserved */
            reserved: string;
            /** Available */
            available: string;
            /** Version */
            version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OrganizationResponse */
        OrganizationResponse: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Valuation Method */
            valuation_method: string;
        };
        /** PositionListResponse */
        PositionListResponse: {
            /** Items */
            items: components["schemas"]["InventoryPositionResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * StockCondition
         * @enum {string}
         */
        StockCondition: "sellable" | "quarantined" | "damaged" | "expired";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_positions_v1_inventory_positions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Development-User"?: string | null;
                "X-Development-Organization"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_inventory_v1_inventory_adjustments_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match"?: string | null;
                "X-Development-User"?: string | null;
                "X-Development-Organization"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryAdjustmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdjustmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_organization_v1_organizations_current_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Development-User"?: string | null;
                "X-Development-Organization"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roles_v1_roles_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Development-User"?: string | null;
                "X-Development-Organization"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approval_policies_v1_approval_policies_get: {
        parameters: {
            query?: {
                action_type?: string | null;
            };
            header?: {
                "X-Development-User"?: string | null;
                "X-Development-Organization"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalPolicyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feature_flags_v1_feature_flags_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Development-User"?: string | null;
                "X-Development-Organization"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
